
#Download

FNDLOAD apps/Y1bMB3qd 0 Y DOWNLOAD $XDO_TOP/patch/115/import/xdotmpl.lct  T_XXSVARDRILLREV.ldt XDO_DS_DEFINITIONS X_TEMPLATES TEMPLATE_CODE="XXSVARDRILLREV" APPLICATION_SHORT_NAME="XBOL" DATA_SOURCE_CODE="XXSVARDRILLREV"

FNDLOAD apps/Y1bMB3qd O Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct C_XXSVARDRILLREV.ldt PROGRAM APPLICATION_SHORT_NAME="XBOL" CONCURRENT_PROGRAM_NAME="XXSVARDRILLREV"

FNDLOAD apps/Y1bMB3qd O Y DOWNLOAD $FND_TOP/patch/115/import/afcpreqg.lct R_Receivables_All.ldt REQUEST_GROUP REQUEST_GROUP_NAME="Receivables All" APPLICATION_SHORT_NAME="AR"


#Upload


# XML
FNDLOAD apps/Y1bMB3qd 0 Y UPLOAD $XDO_TOP/patch/115/import/xdotmpl.lct T_XXSVARDRILLREV.ldt - CUSTOM_MODE="FORCE"

#Programas 
FNDLOAD apps/aY1bMB3qd O Y UPLOAD $FND_TOP/patch/115/import/afcpprog.lct C_XXSVARDRILLREV.ldt 

#Request Group
FNDLOAD apps/apps@db O Y UPLOAD $FND_TOP/patch/115/import/afcpreqg.lct R_Receivables_All.ldt 