begin
 
DELETE FROM XDO_DS_DEFINITIONS_TL
  WHERE APPLICATION_SHORT_NAME = 'XBOL'
  AND DATA_SOURCE_CODE LIKE '%XXSVARDRILLREV%';
 
  DELETE FROM XDO_DS_DEFINITIONS_B
  WHERE APPLICATION_SHORT_NAME = 'XBOL'
  AND DATA_SOURCE_CODE LIKE '%XXSVARDRILLREV%';
  
COMMIT;
 
 
DELETE FROM XDO_TEMPLATES_TL
  WHERE APPLICATION_SHORT_NAME = 'XBOL'
  AND TEMPLATE_CODE LIKE '%XXSVARDRILLREV%';
 
  DELETE FROM XDO_TEMPLATES_B
  WHERE APPLICATION_SHORT_NAME = 'XBOL'
  AND TEMPLATE_CODE LIKE '%XXSVARDRILLREV%';
  
COMMIT;
 
DELETE FROM XDO.XDO_LOBS WHERE LOB_CODE LIKE '%XXSVARDRILLREV%';

COMMIT;

end;