/* Formatted on 10/6/2014 12:31:14 PM (QP5 v5.139.911.3011) */
SELECT *
  FROM all_tab_columns
 WHERE column_name LIKE 'UNROUNDED_ACCOUNTED_DR';


SELECT * FROM XX_AH_XLA_AR_REC_AEL_GL_V;


SELECT LEDGER_NAME ,CURRENCY_CODE
      ,PERIOD_NAME  ,USER_JE_SOURCE_NAME
      ,GL_USER   ,JE_CREATION_DATE
      ,JE_LINE_NUM  ,JE_STATUS
      ,JE_NAME ,ACCOUNTED_DR
      ,ACCOUNTED_CR  ,AR_USER
      ,AR_CREATION_DATE   ,TRX_TYPE_NAME
      ,TRX_NUMBER   ,LINE_NUMBER
      ,LINE_TYPE  ,LINE_DESCRIPTION
      ,CUSTOMER_REFERENCE ,PARTY_NAME
      ,SEGMENT1  ,COMPANY_DESC
      ,SEGMENT2  ,ACCOUNT_DESC
      ,SEGMENT3  ,LOCAL_DESC
      ,SEGMENT4  ,COST_CENTER_DESC
      ,SEGMENT5   ,TERRITORY_DESC
      ,SEGMENT6  ,BUSINESS_UNIT_DESC
      ,SEGMENT7  ,CATEGORY_DESC
      ,SEGMENT8  ,PRODUCT_DESC
      ,SEGMENT9  ,PROJECT_DESC
      ,SEGMENT10  ,INTERCOMPANY_DESC
      ,SEGMENT11  ,FLOW_DESC
      ,SEGMENT12  ,FUTURE1_DESC
      ,SEGMENT13  ,FUTURE2_DESC
  FROM XXSV_GL_JE_AR_TRX_CUST_REPORT
 WHERE period_name = '12-13'
   AND ledger_id = 2245;


SELECT SEGMENT1
      ,SEGMENT2
      ,ACCOUNT_DESC
      ,SEGMENT3
      ,SEGMENT4
      ,SEGMENT5
      ,SEGMENT6
      ,BUSINESS_UNIT_DESC
      ,SEGMENT7
      ,SEGMENT8
      ,PRODUCT_DESC
      ,SEGMENT9
      ,SEGMENT10
      ,SEGMENT11
      ,SEGMENT12
      ,SEGMENT13
      ,JE_NAME
      ,period_name
      ,CURRENCY_CODE
      ,ACCOUNTED_DR
      ,ACCOUNTED_CR
      ,LINE_DESCRIPTION
  FROM XXSV_GL_JE_AR_TRX_CUST_REPORT
 WHERE period_name = '12-13'
   AND ledger_id = 2245;


grant select on XXSV_GL_JE_AR_TRX_CUST_REPORT to apps;

create or replace view XXSV_GL_JE_AR_TRX_CUST_REPORT
as 
SELECT GLL.LEDGER_ID
      ,GLL.NAME LEDGER_NAME
      ,GLL.CURRENCY_CODE
      ,GJH.period_name
      ,GJS.USER_JE_SOURCE_NAME
      ,GJH.JE_BATCH_ID
      ,GJH.JE_HEADER_ID
      ,GLL.CHART_OF_ACCOUNTS_ID
      ,FNU.USER_NAME  GL_USER
      ,GJH.CREATION_DATE JE_CREATION_DATE
      ,GIR.JE_LINE_NUM
      ,XX_UTILITIES.LOOKUP_MEANING ( 'MJE_BATCH_STATUS',GJL.STATUS) JE_STATUS
      ,GJH.NAME je_name
      /*,XAL.ENTERED_DR XLAL_ENTERED_DR */
      /*,XAL.ENTERED_CR XLAL_ENTERED_CR */
      ,XDL.UNROUNDED_ACCOUNTED_DR ACCOUNTED_DR
      ,XDL.UNROUNDED_ACCOUNTED_CR ACCOUNTED_CR
      ,FNUAR.USER_NAME  AR_USER
      ,RCT.CREATION_DATE AR_CREATION_DATE
      ,CTT.NAME TRX_TYPE_NAME
      ,RCT.trx_number
      ,CTL.LINE_NUMBER
      ,XX_UTILITIES.LOOKUP_MEANING ( 'AUTOGL_TYPE', RCTGD.ACCOUNT_CLASS) LINE_TYPE
      ,ctl.DESCRIPTION  LINE_DESCRIPTION 
      ,CA.ORIG_SYSTEM_REFERENCE CUSTOMER_REFERENCE
      ,hzp.party_name
      /*,DECODE (RCTGD.ACCOUNT_CLASS, 'REC', 'CT', 'CTLGD') SOURCE_TABLE*/
      /*,DECODE (
               RCTGD.ACCOUNT_CLASS
              ,'REC', RCT.CUSTOMER_TRX_ID
              ,RCTGD.CUST_TRX_LINE_GL_DIST_ID
              )
          SOURCE_ID */
      /*,XAL.ACCOUNTED_DR XLAL_ACCOUNTED_DR*/
      /*,XAL.ACCOUNTED_CR XLAL_ACCOUNTED_CR*/
--      ,CTL.CUSTOMER_TRX_ID
--      ,RCTGD.CREATION_DATE
      ,RCTGD.CODE_COMBINATION_ID
      ,GLCC.segment1
      ,XX_UTILITIES.FLEX_VALUE_DESCRIPTION('XX_GL_MIC_COMPANY_VS',GLCC.segment1) COMPANY_DESC 
        ,GLCC.segment2
        ,XX_UTILITIES.FLEX_VALUE_DESCRIPTION('XX_GL_MIC_ACCOUNT_VS',GLCC.segment2) ACCOUNT_DESC
        ,GLCC.segment3
        ,XX_UTILITIES.FLEX_VALUE_DESCRIPTION('XX_GL_MIC_LOCAL_VS',GLCC.segment3) LOCAL_DESC
        ,GLCC.segment4
        ,XX_UTILITIES.FLEX_VALUE_DESCRIPTION('XX_GL_MIC_COST_CENTER_VS',GLCC.segment4) COST_CENTER_DESC
        ,GLCC.segment5
        ,XX_UTILITIES.FLEX_VALUE_DESCRIPTION('XX_GL_MIC_TERRITORY_VS',GLCC.segment5) TERRITORY_DESC
        ,GLCC.segment6
        ,XX_UTILITIES.FLEX_VALUE_DESCRIPTION('XX_GL_MIC_BUSINESS_UNIT_VS',GLCC.segment6) BUSINESS_UNIT_DESC  
        ,GLCC.segment7
        ,XX_UTILITIES.FLEX_VALUE_DESCRIPTION('XX_GL_MIC_CATEGORY_VS',GLCC.segment7) CATEGORY_DESC  
        ,GLCC.segment8
        ,XX_UTILITIES.FLEX_VALUE_DESCRIPTION('XX_GL_MIC_PRODUCT_VS',GLCC.segment8) PRODUCT_DESC
        ,GLCC.segment9
        ,XX_UTILITIES.FLEX_VALUE_DESCRIPTION('XX_GL_MIC_PROJECT_VS',GLCC.segment9) PROJECT_DESC
        ,GLCC.segment10
        ,XX_UTILITIES.FLEX_VALUE_DESCRIPTION('XX_GL_MIC_INTERCOMPANY_VS',GLCC.segment10) INTERCOMPANY_DESC
        ,GLCC.segment11
        ,XX_UTILITIES.FLEX_VALUE_DESCRIPTION('XX_GL_MIC_FLOW_VS',GLCC.segment11) FLOW_DESC
        ,GLCC.segment12
        ,XX_UTILITIES.FLEX_VALUE_DESCRIPTION('XX_GL_MIC_FUTURE1_VS',GLCC.segment12) FUTURE1_DESC
        ,GLCC.segment13
        ,XX_UTILITIES.FLEX_VALUE_DESCRIPTION('XX_GL_MIC_FUTURE2_VS',GLCC.segment13) FUTURE2_DESC
  FROM APPS.GL_JE_HEADERS GJH
      ,APPS.GL_JE_SOURCES GJS
      ,APPS.GL_JE_LINES GJL
      ,APPS.FND_USER FNU
      ,APPS.FND_USER FNUAR
      ,APPS.GL_CODE_COMBINATIONS_KFV GLCC
      ,APPS.GL_IMPORT_REFERENCES GIR
      ,XLA.XLA_AE_LINES XAL
      ,XLA.XLA_AE_HEADERS XAH
      ,XLA.XLA_EVENTS XE
      ,XLA.XLA_TRANSACTION_ENTITIES XTE
      ,XLA.XLA_DISTRIBUTION_LINKS XDL
      ,APPS.GL_LEDGERS GLL
      ,APPS.RA_CUST_TRX_LINE_GL_DIST_ALL    RCTGD
      ,apps.RA_CUSTOMER_TRX_LINES_all       CTL
      ,APPS.RA_CUSTOMER_TRX_ALL             RCT
      ,APPS.RA_CUST_TRX_TYPES_ALL           CTT
      ,apps.HZ_CUST_ACCOUNTS                CA
      ,apps.hz_parties                      hzp
 WHERE GJH.CREATED_BY = FNU.USER_ID
   and RCT.CREATED_BY = FNUAR.USER_ID
   AND GJH.LEDGER_ID = GLL.LEDGER_ID
   AND GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
   AND GJH.JE_SOURCE = GJS.JE_SOURCE_NAME
   AND GJS.LANGUAGE = USERENV ('LANG')
   AND XAL.CODE_COMBINATION_ID = GLCC.CODE_COMBINATION_ID
   AND GJL.JE_HEADER_ID = GIR.JE_HEADER_ID
   AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
   /*AND GJL.STATUS != 'P'*/
   AND GJH.ACTUAL_FLAG = 'A'
   AND GIR.GL_SL_LINK_TABLE = XAL.GL_SL_LINK_TABLE
   AND GIR.GL_SL_LINK_ID = XAL.GL_SL_LINK_ID
   AND XAL.AE_HEADER_ID = XAH.AE_HEADER_ID
   AND XAH.EVENT_ID = XE.EVENT_ID
   AND XAH.AE_HEADER_ID = XDL.AE_HEADER_ID
   AND XAL.AE_LINE_NUM = XDL.AE_LINE_NUM
   AND (NVL (XAL.ACCOUNTED_DR, 0) != 0
     OR  NVL (XAL.ACCOUNTED_CR, 0) != 0)
   AND XE.ENTITY_ID = XTE.ENTITY_ID
   AND XAH.APPLICATION_ID = XAL.APPLICATION_ID
   AND XAL.APPLICATION_ID = XTE.APPLICATION_ID
   AND XTE.APPLICATION_ID = XDL.APPLICATION_ID
   AND XE.APPLICATION_ID = XTE.APPLICATION_ID
   AND XAH.APPLICATION_ID = XE.APPLICATION_ID
   AND XAH.APPLICATION_ID = 222
   AND XDL.SOURCE_DISTRIBUTION_ID_NUM_1 = RCTGD.CUST_TRX_LINE_GL_DIST_ID
   and RCTGD.CUSTOMER_TRX_LINE_ID = CTL.CUSTOMER_TRX_LINE_ID(+) /* Dist sin linea */
   and RCTGD.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID
   and RCT.CUST_TRX_TYPE_ID =   CTT.CUST_TRX_TYPE_ID 
   and RCT.BILL_TO_CUSTOMER_ID = ca.CUST_ACCOUNT_ID
   and ca.party_id = hzp.party_id
   AND XTE.ENTITY_CODE = 'TRANSACTIONS'
   AND GJH.JE_SOURCE = 'Receivables'
--   AND GJH.period_name ='12-13' /* P_PERIOD_NAME */
--   AND GJH.ledger_id = 2245 /* P_LEDGER_ID */
--   AND GJL.JE_HEADER_ID = 763933
   AND GJH.JE_CATEGORY IN ('Sales Invoices', 'Credit Memos', 'Debit Memos', 'Chargebacks');



SELECT rct.trx_number, ctl.line_number, ctl.*
  FROM RA_CUSTOMER_TRX_ALL RCT, RA_CUSTOMER_TRX_LINES_all CTL
 WHERE RCT.CUSTOMER_TRX_ID = 5142652
   AND CTL.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID;

SELECT Rct.Trx_Number, RCTGD.*
  FROM Ra_Customer_Trx_All Rct, RA_CUST_TRX_LINE_GL_DIST_ALL RCTGD
 WHERE Rct.Customer_Trx_Id = 5142652
   AND Rct.Customer_Trx_ID = RCTGD.CUSTOMER_TRX_ID;

SELECT *
  FROM apps.fnd_flex_value_sets
 WHERE FLEX_VALUE_SET_NAME LIKE 'XX%GL%VS';


SELECT FLEX_VALUE_SET_NAME, fvt.DESCRIPTION, fvs.*
  FROM apps.FND_FLEX_VALUES fv
      ,apps.fnd_flex_value_sets fvs
      ,apps.FND_FLEX_VALUES_TL fvt
 WHERE FLEX_VALUE IN ('REV', 'REC')
   --     and FLEX_VALUE_SET_NAME like 'GL%'
   AND fvs.FLEX_VALUE_SET_ID = fv.FLEX_VALUE_SET_ID
   AND fvt.flex_value_id = fvt.flex_value_id
   AND fvt.language = 'US'
--     and fvt.DESCRIPTION like 'Posted%'
;
SELECT *
  FROM apps.FND_FLEX_VALUES fv
--where FLEX_VALUE in ('REV')
;
SELECT LOOKUP_TYPE
      ,LOOKUP_CODE
      ,MEANING
      ,DESCRIPTION
  FROM FND_LOOKUP_VALUES
 WHERE LANGUAGE = 'US'
   --     and LOOKUP_CODE in ('REV','REC')
   --   and LOOKUP_CODE in ('P')
   AND MEANING IN ('Posted', 'Unposted')
--     and LOOKUP_TYPE  like 'BATCH_STATUS'
;
SELECT *
  FROM AR_LOOKUPS
 WHERE LOOKUP_TYPE = 'AUTOGL_TYPE'
--      and  LANGUAGE = 'ESA'
;
SELECT *
  FROM APPS.GL_JE_HEADERS GJH, APPS.GL_JE_LINES GJL
 WHERE GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
   AND GJH.ledger_id IN (2245, 2247)
   AND GJH.period_name LIKE '%13'
   AND GJL.STATUS != 'P';